language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -B test

after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - "master"
